services:
  ecommercesolution.orderservice:
    image: ${DOCKER_REGISTRY-}ecommercesolutionorderservice
    build:
      context: .
      dockerfile: ECommerceSolution.OrderService/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - MONGODB_PORT=27017
     - MONGODB_HOST=mongodb-container
     - MONGODB_DATABASE=OrdersDatabase
     - UsersMicroserviceName=api-gateway
     - UsersMicroservicePort=8080
     - ProductsMicroserviceName=api-gateway
     - ProductsMicroservicePort=8080
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - RABBITMQ_HOST=rabbitmq
     - RABBITMQ_USER=admin
     - RABBITMQ_PASSWORD=admin
     - RABBITMQ_PORT=5672
     - RABBITMQ_PRODUCTS_EXCHANGE=products.exchange
    ports:
     - "7000:8080"
    networks:
     - orders-mongodb-network
     - ecommerce-network
    depends_on:
     - mongodb-container
     - rabbitmq

  mongodb-container:
    image: mongo:latest
    ports:
     - "27017:27017"
    volumes:
     - "C:/LiFe/.NET Microservice Proj/ECommerceMicroservices_Docker_Contrainers/DatabaseSQLScript/OrdersTableSQLScript:/docker-entrypoint-initdb.d"
    networks:
     - orders-mongodb-network

  products-microservice:
    image: products-microservice:latest
    environment:
     - ASPNETCORE_HTTP_PORTS=8080
     - ASPNETCORE_ENVIRONMENT=Development
     - MYSQL_HOST=mysql-container
     - MYSQL_PORT=3306
     - MYSQL_DATABASE=ecommerceproductsdatabase
     - MYSQL_PASSWORD=admin
     - MYSQL_USER=root
     - RABBITMQ_HOST=rabbitmq
     - RABBITMQ_USER=admin
     - RABBITMQ_PASSWORD=admin
     - RABBITMQ_PORT=5672
     - RABBITMQ_PRODUCTS_EXCHANGE=products.exchange
    ports:
     - "6001:8080"
    networks:
     - products-mysql-network
     - ecommerce-network
    depends_on:
     - mysql-container

  mysql-container:
    image: mysql:9.6.0
    environment:
     - MYSQL_ROOT_PASSWORD=admin
    ports:
     - "3307:3306"
    volumes:
     - "C:/LiFe/.NET Microservice Proj/ECommerceMicroservices_Docker_Contrainers/DatabaseSQLScript/ProductsTableSQLScript:/docker-entrypoint-initdb.d"
    networks:
     - products-mysql-network
    

  users-microservice:
    image: users-microservice:latest
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - POSTGRES_HOST=postgres-container
     - POSTGRES_PORT=5432
     - POSTGRES_DATABASE=eCommerceUsers
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=admin
    ports:
     - "5000:2929"
    networks:
     - users-postgres-network
     - ecommerce-network
    depends_on:
     - postgres-container

  postgres-container:
    image: postgres:latest
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=eCommerceUsers
    ports: 
     - "5433:5432"
    volumes:
     - "C:/LiFe/.NET Microservice Proj/ECommerceMicroservices_Docker_Contrainers/DatabaseSQLScript/UsersTableSQLScript:/docker-entrypoint-initdb.d"
    networks:
     - users-postgres-network

  redis:
    image: redis:latest
    ports:
     - "6379:6379"
    volumes:
     - "C:/LiFe/.NET Microservice Proj/redis-cache:/data"
    networks:
     - ecommerce-network
   
  api-gateway:
    image: api-gateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
     - "4000:8080"
    networks:
     - ecommerce-network
    depends_on:
     - ecommercesolution.orderservice

  rabbitmq:
    image: rabbitmq:management
    ports:
     - "5673:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=admin
    networks:
     - ecommerce-network

networks:
 orders-mongodb-network:
  driver: bridge    
 products-mysql-network:
  driver: bridge
 users-postgres-network:
  driver: bridge
 ecommerce-network:
  driver: bridge
  
